<?xml version="1.0"?>
<package format="3">
  <name>robot_control_ur3</name>
  <version>0.0.1</version>
  <description>Control y simulacion Gazebo para UR3 + gripper en la celda.</description>
  <maintainer email="glenguerrero82@gmail.com">Glen Guerrero</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>robot_description_ur3</exec_depend>
  <exec_depend>robot_cell_moveit_ur3</exec_depend>
  <exec_depend>ur_description</exec_depend>
  <exec_depend>ros_gz_sim</exec_depend>
  <exec_depend>ros_gz_bridge</exec_depend>
  <exec_depend>gz_ros2_control</exec_depend>
  <exec_depend>joint_state_broadcaster</exec_depend>
  <exec_depend>joint_trajectory_controller</exec_depend>
  <exec_depend>controller_manager</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>xacro</exec_depend>
  <exec_depend>rviz2</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
